- CONTRIBUTING.rst
- README.md
Adjusted README.md
Added CONTRIBUTING.rst
> Minor Modifications/Addtions

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-request-or-enhancement.md
- .github/ISSUE_TEMPLATE/question.md
- .github/pull_request_template.md
- defaults/main.yml
- tasks/main.yml
- tasks/parse_etc_password.yml
- tasks/section_2/cis_2.1.x.yml
Issues Addressed:
#20 - Typo in default/main.yml default value
Enhancements:
- Added issue templates
- Added PR template
> Added issue templates and issue fixes

- .github/pull_request_template.md
Added Issue and PR templates. Addressed one issue that was a typo in a variable value
**Any Related Open Issues:**
#20 - Typo in defaults/main.yml default value
Locally and via pipeline using RHEL8 and CENTOS8
> Added Issue/PR Templates and issue fixes

- .github/pull_request_template.md
Updated PR template formatting 
None
Updated PR template for better information gathering and formatting
N/A
> Updated PR template formatting

- tasks/section_5/cis_5.5.x.yml
Signed-off-by: Mark Bolwell <mark.bollyuk@gmail.com>
Issue Fix
#46 thanks to seniormuffinman
Manually
> added fix for issue #46

- tasks/main.yml
- tasks/section_1/cis_1.2.x.yml
- templates/ansible_vars_goss.yml.j2
Update to audit content
Old settings now updated and tags can be used for audit summary
manually
> Audit template

- tasks/section_1/cis_1.1.x.yml
- tasks/section_2/cis_2.1.x.yml
- tasks/section_4/cis_4.2.1.x.yml
- tasks/section_4/cis_4.3.yml
- tasks/section_5/cis_5.3.x.yml
- tasks/section_6/cis_6.1.x.yml
- templates/audit/ubtu20cis_4_1_15_actions.rules.j2
Fixed typo in 4.1.15 and typo in 2.1.1.4
- #54 
- #55 
None
Locally
> Issue 54 and 55 fixes

- .github/workflows/linux_benchmark_testing.yml
- .github/workflows/update_galaxy.yml
- .yamllint
- Changelog.md
- LICENSE
- tests/inventory
- tests/test.yml
Updated ansible lint inline with galaxy requirements
N/A
> Galaxy update

- Changelog.md
- defaults/main.yml
- handlers/main.yml
- tasks/section_1/cis_1.1.x.yml
var/tmp fix
handlers removed unnecessary src being provided
removed default/main.yml vartmp vars as not required
#84 
Manually
> Issue 84 addressed 

- .github/workflows/devel_pipeline_validation.yml
- README.md
> updated discord link

- tasks/main.yml
- tasks/post.yml
- tasks/pre_remediation_audit.yml
- tasks/section_1/cis_1.1.2.x.yml
- tasks/section_1/cis_1.1.3.x.yml
- tasks/section_1/cis_1.1.4.x.yml
- tasks/section_1/cis_1.1.5.x.yml
- tasks/section_1/cis_1.1.6.x.yml
- tasks/section_1/cis_1.1.7.x.yml
- tasks/section_1/cis_1.3.x.yml
- tasks/section_1/cis_1.4.x.yml
- tasks/section_1/cis_1.6.x.yml
- tasks/section_1/main.yml
- tasks/section_2/cis_2.2.x.yml
- tasks/section_2/cis_2.4.yml
- tasks/section_2/main.yml
- tasks/section_3/cis_3.4.1.x.yml
- tasks/section_3/cis_3.4.2.x.yml
- tasks/section_3/cis_3.4.3.x.yml
- tasks/section_3/main.yml
- tasks/section_4/cis_4.4.x.yml
- tasks/section_4/cis_4.5.1.x.yml
- tasks/section_4/main.yml
- tasks/section_5/cis_5.1.1.x.yml
- tasks/section_5/cis_5.1.2.x.yml
- tasks/section_5/main.yml
- tasks/section_6/cis_6.1.x.yml
- tasks/section_6/cis_6.2.x.yml
- tasks/section_6/main.yml
Added file to import_tasks: module lines
#88 
Manually
> Import tasks update

- README.md
- collections/requirements.yml
- tasks/section_1/cis_1.4.x.yml
Overall Review of Changes:
Updated collections requirements file following changes by ansible-galaxy
lint update
How has this been tested?:
Not Required
> collections and lint update

- tasks/section_5/cis_5.1.2.x.yml
fixes typo in cron entry rsyslog.conf
corrected cron entry to match CIS control
n/a
tested locally
> fixes cron typo in rsyslog.conf generation

- tasks/section_6/cis_6.2.x.yml
See Issue 112
Fixes Issue #112
n/a
tested locally
> removes unexpected variable

- tasks/section_5/cis_5.2.3.x.yml
Adds discovery method used by benchmark and most scanners to find priv files
Improves privileged cmd collection
Improves privileged cmd collection
tested locally
> Fixes list privileged cmd collection to match benchmark

- tasks/LE_audit_setup.yml
Fixed the conditional for arm64 in preperation for arm audits
NR
> fixed test for the arm64 conditional

- .github/workflows/devel_pipeline_validation.yml
- .github/workflows/main_pipeline_validation.yml
- .github/workflows/update_galaxy.yml
- Changelog.md
- defaults/main.yml
- tasks/audit_only.yml
- tasks/post_remediation_audit.yml
- tasks/pre_remediation_audit.yml
- tasks/prelim.yml
- vars/audit.yml
Issues and audit improvements
updates to new workflow
#148 thanks to karlg100
audit updates
improved layout on results
standardized output and layout
Manually locally
> Issue 148, audit and workflow updates

- .pre-commit-config.yaml
- tasks/section_5/cis_5.1.1.1.x.yml
pre-commit updates
devel pipeline
> devel to main release

- defaults/main.yml
- tasks/fetch_audit_output.yml
- tasks/main.yml
- tasks/post_remediation_audit.yml
- tasks/pre_remediation_audit.yml
- templates/etc/ansible/compliance_facts.j2
Added ability to pull fetch audit results
Added ansible facts details 
Removed jmespath dependancy
Manually
> Fetch and facts

- defaults/main.yml
- tasks/LE_audit_setup.yml
- tasks/audit_only.yml
- tasks/fetch_audit_output.yml
- tasks/main.yml
- tasks/post_remediation_audit.yml
- tasks/pre_remediation_audit.yml
- vars/audit.yml
Please ensure that you have understood contributing guide
Ensure all commits are signed-by and gpg signed
Audit components updated
Manually
> Updated audit components

- .github/workflows/devel_pipeline_validation.yml
- .github/workflows/main_pipeline_validation.yml
- .gitignore
- .pre-commit-config.yaml
- LICENSE
- defaults/main.yml
- tasks/LE_audit_setup.yml
- tasks/audit_only.yml
- tasks/fetch_audit_output.yml
- tasks/main.yml
- tasks/post_remediation_audit.yml
- tasks/pre_remediation_audit.yml
- templates/etc/ansible/compliance_facts.j2
- templates/etc/chrony/sources.d/time.sources.j2
- templates/etc/systemd/timesyncd.conf.d/50-timesyncd.conf.j2
- vars/audit.yml
Please ensure that you have understood contributing guide
Ensure all commits are signed-by and gpg signed
pre-commit
audit enhancements
workflow updates
ansible facts
alignment
lint
typos
Pipeline and devel
> Release of v2.0.1 to main
